"""MarketDataProvider Protocol — single Börsdata adapter contract."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class MarketDataProvider(Protocol):
    def get_instruments(self) -> list[dict[str, Any]]: ...

    def get_markets(self) -> list[dict[str, Any]]: ...

    def get_branches(self) -> list[dict[str, Any]]: ...

    def get_sectors(self) -> list[dict[str, Any]]: ...

    def get_countries(self) -> list[dict[str, Any]]: ...

    def get_translation_metadata(self) -> list[dict[str, Any]]: ...

    def get_kpi_metadata(self) -> list[dict[str, Any]]: ...

    def get_report_metadata(self) -> list[dict[str, Any]]: ...

    def get_kpis(
        self, ins_id: int, kpi_id: int, calc_group: str, calc: str
    ) -> dict[str, Any] | None: ...

    def get_kpi_history(
        self, ins_id: int, kpi_id: int, report_type: str, price_type: str
    ) -> list[dict[str, Any]]: ...

    def get_kpi_summary(self, ins_id: int, report_type: str) -> dict[str, Any] | None: ...

    def get_reports(self, ins_ids: list[int], *, original: int = 0) -> list[dict[str, Any]]: ...

    def get_stock_prices(
        self, ins_id: int, *, max_count: int | None = None
    ) -> list[dict[str, Any]]: ...

    def get_dividends(self) -> list[dict[str, Any]]: ...

    def get_insider(self) -> list[dict[str, Any]]: ...

    def get_buyback(self) -> list[dict[str, Any]]: ...

    def get_shorts(self) -> list[dict[str, Any]]: ...

    def get_stock_splits(self, *, from_date: str | None = None) -> list[dict[str, Any]]: ...

    def get_report_calendar(self) -> list[dict[str, Any]]: ...
